[build]
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

[functions."render-background"]
  background = true
  included_files = ["node_modules/ffmpeg-static/ffmpeg", "node_modules/ffprobe-static/bin/linux/x64/ffprobe"]

[functions."process-background"]
  background = true
  included_files = ["node_modules/ffmpeg-static/ffmpeg", "node_modules/ffprobe-static/bin/linux/x64/ffprobe"]
